local g = vim.g
local o = vim.opt

g.mapleader = ' '
g.maplocalleader = ' '
g.markdown_recommended_style = 0

o.mouse=""
o.sessionoptions = 'buffers,curdir,folds,winpos,winsize'
o.formatoptions = 'jcroqlnt'
o.grepformat = '%f:%l:%c:%m'
o.grepprg = 'rg --vimgrep'
o.clipboard = 'unnamedplus'
o.cmdheight = 1
o.lazyredraw = true
o.list = false
o.termguicolors = true
o.syntax = 'on'
g.noshowmode = true
o.errorbells = false
o.smartcase = true
o.tabstop = 2
o.softtabstop = 2
o.shiftwidth = 2
o.expandtab = true
o.showmode = false
o.backup = false
o.undodir = vim.fn.stdpath('config') .. '/undodir'
o.undofile = true
o.incsearch = true
o.inccommand = 'nosplit'
o.hidden = true
o.completeopt = 'menu,menuone,noselect'
o.confirm = true
o.shortmess:append({ I = true })
o.signcolumn = 'yes'
o.so = 999
o.redrawtime = 1500
o.timeoutlen = 500
o.updatetime = 100
o.fillchars = { eob = ' ', vert = '▎', diff = '╱' }
o.number = true
o.pumheight = 10
o.scrolloff = 4
o.shiftround = true
o.sidescrolloff = 0
o.smartindent = true
o.spelllang = { 'en' }
o.splitbelow = true
o.splitright = true
o.wildmode = 'longest:full,full'
o.winminwidth = 5
o.wrap = true
o.swapfile = false
